### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-client-packaging#3]
`tezos-client` is a bit bad name, it makes one think that the code of `tezos-client` is in this repo, but here we only have some scripts for packaging. We need a better name. `tezos-client-nix` or anything that has `nix` in name is also a bit bad because the fact that `nix` is used is just implementation detail.
TODO: specify name.
Even though the repo is new, it should be done carefully to avoid breaking links (e. g. to buildkite). Also maybe we'll have to change something in buildkite itself.

**Comment by gromakovsky** [comment]
So far the best name we could come up with is `tezos-client-packaging`.

**Comment by rvem** [comment]
I've renamed repo and changed the link to it in the CI (also renamed pipeline), and it seems, that's all that needs to be changed

**Comment by gromakovsky** [comment]
In README there is a link to https://buildkite.com/serokell/tezos-client/builds/latest?branch=master

Currently it redirects to https://buildkite.com/serokell/tezos-client-packaging/builds/23, but it would be good to add `-packaging` to it anyway.

**Comment by gromakovsky** [comment]
There's also a link in the PR template, but I've removed it in #6.
